name: Java and Selenide CI run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: 16
    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh 
    - name: Run tests
      run: mvn test --file pom.xml
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
           name: Generate Report
           path: reports/jest-*.xml
           reporter: java-junit
