name: Java and Selenide CI run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  UI-tests:
    strategy:
      matrix:
        feature_name: [Products, Login]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: ${{ matrix.feature_name }}
        run: mvn test --file pom.xml -Dcucumber.filter.tags=@${{ matrix.feature_name }}
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: ${{ matrix.feature_name }} - report
          path: target/surefire-reports/*.xml
          reporter: java-junit
